version: "3.9"
services:
  proxy:
    build: .
    image: minidfx/reverse-proxy:alpha
    ports:
      - 80:80
      - 443:443
    environment:
      - PASSWORDS=foo.localhost=dXNlcm5hbWU6cGFzc3dvcmQ= # protect the foo.localhost domain with following the username 'username' and the password 'password'.
      - UPSTREAMS=foo.localhost=http://www.example.com,bar.localhost=http://www.perdu.com
      - STAGING=true # Set to true for test purpose
      - EMAIL=<your-email>
