version: "3.9"
services:
  proxy:
    build: .
    image: minidfx/reverse-proxy:alpha
    ports:
      - 80:4000
      - 443:4443
    environment:
      - UPSTREAMS=foo.localhost=http://www.example.com,bar.localhost=http://www.perdu.com
      - STAGING=true # Set to true for test purpose
      - EMAIL=<your-email>
